# -*- coding: utf-8 -*-

"""
This module contains the Built-in sinks.
"""
import logging

import cv2
import numpy as np
import csv

from videoanalytics.pipeline import Sink

class VideoWriter(Sink):
    '''
    Writes video to a file using OpenCV writer.

    This component **READS** the following entries in the global context:

    +-------------------+-----------------------------------------------------+
    | Variable name     | Description                                         |
    +===================+============+==========+=============================+
    | INPUT_FPS         | Input video FPS.                                    |
    +-------------------+-----------------------------------------------------+
    | INPUT_WIDTH       | Input video width in pixels.                        |
    +-------------------+-----------------------------------------------------+
    | INPUT_HEIGHT      | Input video height in pixels.                       |
    +-------------------+-----------------------------------------------------+
    | FRAME             | Numpy array representing the frame.                 |
    +-------------------+-----------------------------------------------------+

    Args:
        name(str): the component unique name.
        context (dict): The global context.         
        filename (str): output video filename.
        output_format (str): output format (default to XVID). 
                             Any format supported by OpenCV VideoWriter_fourcc.        
    '''
    
    logger = logging.getLogger(__name__)

    def __init__(self, name, context, filename,output_format="XVID",fps=None,width=None,height=None):
        super().__init__(name,context)
        self.filename = filename
        codec = cv2.VideoWriter_fourcc(*output_format)

        if fps is None and self.context["INPUT_FPS"]:
            fps = self.context["INPUT_FPS"]

        if width is None and self.context["INPUT_WIDTH"]:
            width = self.context["INPUT_WIDTH"]

        if height is None and self.context["INPUT_HEIGHT"]:
            height = self.context["INPUT_HEIGHT"]            

        self.out = cv2.VideoWriter(self.filename, codec, fps, (width, height))
            
    def setup(self):
        pass
    
    def process(self):     
        converted = cv2.cvtColor(self.context["FRAME"], cv2.COLOR_RGB2BGR)        
        self.out.write( converted )
    
    def shutdown(self):
        self.logger.info("Shutting down VideoWriter. Video saved to %s" % self.filename )
        self.out.release()   




class ImageWriter(Sink):
    '''
    Writes the current frame to a image using OpenCV image write.

    This component **READS** the following entries in the global context:

    +-------------------+-----------------------------------------------------+
    | Variable name     | Description                                         |
    +===================+============+==========+=============================+
    | IMG_FILENAME      | Filename for the output image file.                 |
    |                   | Note: this name is generated by ImageSequenceReader.|
    +-------------------+-----------------------------------------------------+
    | INPUT_WIDTH       | Input video width in pixels.                        |
    +-------------------+-----------------------------------------------------+
    | INPUT_HEIGHT      | Input video height in pixels.                       |
    +-------------------+-----------------------------------------------------+
    | FRAME             | Numpy array representing the frame.                 |
    +-------------------+-----------------------------------------------------+

    Args:
        name(str): the component unique name.
        context (dict): The global context.        
        output_path (str): path to store images.        
    '''
    
    logger = logging.getLogger(__name__)

    def __init__(self, name, context, output_path):
        super().__init__(name,context)
        self.output_path = output_path
            
    def setup(self):
        pass
    
    def process(self):    
        cv2.imwrite(self.output_path+self.context["IMG_FILENAME"]+".jpg",
            cv2.cvtColor(self.context["FRAME"], cv2.COLOR_RGB2BGR))
    
    def shutdown(self):
        pass



class VariableCSVWriter(Sink):
    '''
    Stores variables in a CSV.

    This component **READS** the entries matching the variable names specified
    in configurations, example "VARIABLE_1", etc.:

    +-------------------+-----------------------------------------------------+
    | Variable name     | Description                                         |
    +===================+============+==========+=============================+
    | VARIABLE_1        | Variable updated by some component.                 |
    +-------------------+-----------------------------------------------------+
    | VARIABLE_2        | Variable updated by some component.                 |
    +-------------------+-----------------------------------------------------+
    | ...               | ...                                                 |
    +-------------------+-----------------------------------------------------+
    | VARIABLE_N        | Variable updated by some component.                 |
    +-------------------+-----------------------------------------------------+

    Args:        
        name(str): the component unique name.
        context (dict): The global context. 
        filename(str): CSV filename.
        variables_to_write(list): List of variables to write.
    '''
    def __init__(self, name, context,filename,variables_to_write):
        super().__init__(name, context)
        self.csv_file = open(filename, mode='w')
        self.csv_writer = csv.writer(self.csv_file, delimiter=',', quotechar='"', 
                                     quoting=csv.QUOTE_MINIMAL)
        self.variables_to_write = variables_to_write
        self.csv_writer.writerow(["frame_num"]+variables_to_write)

    def setup(self):                
        self.frame_counter = self.context["START_FRAME"]

    def process(self):        
        self.csv_writer.writerow([self.frame_counter]+[self.context[v] for v in self.variables_to_write])            
        self.frame_counter+=1

    def shutdown(self):        
        self.csv_file.close()            



class OpenCVView(Sink):
    '''
    Display current frame (requires desktop).

    This component **READS** the following entries:

    +-------------------+-----------------------------------------------------+
    | Variable name     | Description                                         |
    +===================+============+==========+=============================+
    | FRAME             | Current frame.                                      |
    +-------------------+-----------------------------------------------------+

    Args:        
        name(str): the component unique name.
        context (dict): The global context. 
    '''
    def __init__(self, name, context):
        super().__init__(name, context)

    def setup(self):           
        cv2.namedWindow( "Video", cv2.WINDOW_NORMAL | cv2.WINDOW_FREERATIO);     
        cv2.moveWindow("Video", 150,210);
        cv2.resizeWindow('Video', 1800,1400)

        self.frame_counter = self.context["START_FRAME"]

    def process(self):        
        converted = cv2.cvtColor(self.context["FRAME"], cv2.COLOR_RGB2BGR)     
        cv2.imshow("Video",converted)      
        self.frame_counter+=1

    def shutdown(self):        
        pass
